### PR TITLE
Adding checking for System.Object instances to "coerce3dpointlist" function

### PR DESCRIPTION
**Pull request by stgeorges**
As per: http://discourse.mcneel.com/t/ghpython-problem/21394

### CODE REVIEW

**Comment by sbaer** [comment]
The System.Object test and conversion doesn't make any sense to me. Everything in .NET is derived from System.Object.

**Comment by piac** [comment]
Hi stgeorges

I see why you were looking for this. I will see what options we have for this.
It looks like the best option is the __iter__ method,
http://stackoverflow.com/questions/1952464/in-python-how-do-i-determine-if-an-object-is-iterable

Giulio

**Comment by piac** [comment]
http://mcneel.myjetbrains.com/youtrack/issue/RH-30638

**Comment by stgeorges** [comment]
Thanks guys.

**Pull request closed without merging**
