### PR TITLE
add optional paramter on BlockInstances

### PR DESCRIPTION
**Pull request by goswinr**
This paramter already exist on `BolckInstanceCount` so it would make sense to have it on `BlockInstances ` too.

### CODE REVIEW

**Comment by pearswj** [comment]
Hey @goswinr, thanks for the contribution! As you might have noticed we have different branches for each release-stream of Rhino; service releases (`rhino-6.16`, etc.), internal Rhino 6 builds (`rhino-6.x`) and rhino WIP (`rhino-7.x`). Looks like you've based this change on the Rhino WIP branch, but I reckon we could implement it in 6.16 instead. Sound good? (/cc @acormier)

**Comment by pearswj** [comment]
I've cherry-picked the change onto `rhino-6.16`...

https://github.com/mcneel/rhinoscriptsyntax/compare/rhino-6.16...goswinr/block-Instances?expand=1

**Comment by goswinr** [comment]
@pearswj Ah Ok. I was not sure. the default branch upon openen in the gitub page was 6.x
maybe you should add this note to the readme.

**Comment by pearswj** [comment]
Good idea. Sorry for the extra confusion!

**Comment by acormier** [comment]
Thanks Goswin and Will. Closing this PR that's replaced by #172

**Pull request closed without merging**
