### PR TITLE
Fixes #RH-61534

### PR DESCRIPTION
**Pull request by acormier**

### CODE REVIEW

**Comment by goswinr** [comment]
wouldn't the same change apply to ` IsLayerLocked(layer) ` ?
so that it returns the same as `LayerLocked(layer)` ?

**Comment by acormier** [comment]
You're right they should both report the same. I've made the change so it matches RhinoScript.
Thanks!

**Comment by goswinr** [comment]
Since layers can have three locking states, (and visibility states) I think the docstring should also explain what is returned. for example what  if the layer itself is not locked but still inaccessible because of a locked parent.  What is returned?

**Comment by acormier** [comment]
The wording and names of the variables is confusing (in RhinoScript as well).

The way to think about it is that a layer has `visible` and `locked` attributes that are set with the functions.

Whether the layer is actually visible (same logic for locked) or not depends on the `visible` attribute and where the layer sits in the hierarchy. If the `visible` attribute of a layer is 'false' then it's invisible. If the attribute is 'true' then the layer is visible unless hidden by a parent. There are only 2 states: the layer is visible or not and that's what 'IsLayerVisible' reports.

I agree that the docstrings should be cleaned up. Here's the YT issue: 
https://mcneel.myjetbrains.com/youtrack/issue/RH-62320

Thanks

**Pull request merged**
